### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by kryczek** [GetResponse/PrestaShop#11]
Hi! 
I tried to install yours GetResponse integration, but something went wrong and now in page of my modules I see only this text:

"Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. "

What can I do with this error? Do you have any ideas?
PrestaShop version: 1.7.1.1

**Comment by kryczek** [comment]
I trun on a dev mode and get this info:

> Compile Error: Can't use function return value in write context
500 Internal Server Error - FatalErrorException

**Stack Trace**
in modules/getresponse/classes/GrApi.php at line 269
` 'ipAddress'  => $_SERVER['REMOTE_ADDR'],
        );
        if (!empty(trim($name))) {
            $params['name'] = $name;
        }`

**Comment by rkarkut** [comment]
Hello,
Thank you for contacting us.
Our team will check your issue and fix it.
I will keep you in the loop.

**Comment by amodliszewski** [comment]
Hello, we have fixed that error, however I advise you to update your php to some supported (by php.net) version that gets security updates as the php 5.4 family is abandoned at this point.
