### ISSUE TITLE
PrestaShop 1.7.1 - error during Subscribe via registration page

### ISSUE THREAD

**Issue by Kourtessia** [GetResponse/PrestaShop#12]
Hello GetResponse Team, 

after Set Subscription to Status 'on' an error appears:

{"error":"Incorrect action.","table":""}

You get the same error if you click on Publish under GetResponse forms.

Could you please look at it?

Many thanks for your support

**Comment by mugghe** [comment]
Hello,

I have the same issue for Prestashop 1.6.1.13

Thanks for you support

**Comment by rkarkut** [comment]
Hello,
Thank you for contacting us.

It looks like missing table in you database. Could you try to uninstall our plugin, clear database (prefix getresponse) and try to install it once again?

If there's anything else we can help you with,
please let us know.

**Comment by DerBee** [comment]
Same error over here. Tried your Version 1.6.1.1 and 1.6.1.0 they both did not work on PrestaShop 1.6.1.13 ... tried a re-install and tried via internal upload and external via FTP. :(

**Comment by DerBee** [comment]
Newest Version 1.6.1.3 doesnt change anything in my case ... :o(
