### ISSUE TITLE
Prestashop 1.6.1.13 and module version 1.6.1.2

### ISSUE THREAD

**Issue by DerBee** [GetResponse/PrestaShop#18]
when switching the registration type to registration or form it throws the error: 

{"error":"Incorrect subscription type."}

i didnt get any of the last 3 releases to work on Prestashop 1.6.1.13  als see issue #12 ...

**Comment by DerBee** [comment]
Newest Version 1.6.1.3 doesnt change anything in my case ... :o(

**Comment by kpodemski** [comment]
Same issue for me guys

**Comment by kpodemski** [comment]
The problem was line 93 of AdminGetResponseController.php file, this is how you get the shop url:
$this->context->shop->getBaseURL(true)

for people who use shops on subdirectories getresponse module will not work before this change

**Comment by rkarkut** [comment]
Hello,
I have created a task for our team to solve this issue.
I will keep you in the loop.

Best Regards.

**Comment by kpodemski** [comment]
@rkarkut just look on PR

**Comment by kpodemski** [comment]
@rkarkut ?
